export * from './TimeLine.jsx';
export * from './Blogs.jsx';
export * from './Home.jsx';
export * from './Work.jsx';
export * from './Credits.jsx';
export * from './YouKnowMe.jsx';
export * from './Displaydetails.jsx';
export * from './MainProfile.jsx';
export * from './Navigator.jsx';